import json
from collections import defaultdict
from datetime import UTC, datetime

from scraper import Station

HEADER = "SiiNunit\n{\nlive_stream_def : _nameless.294.f89b.cca0 {\n"
FOOTER = "}\n\n}\n"


def write_sii(stations: list[Station], path: str) -> None:
    lines = [HEADER]
    lines.append(f" stream_data: {len(stations)}\n")
    for i, s in enumerate(stations):
        name = s.name.replace('"', "'")
        genre = s.genre.replace('"', "'")
        lang = s.language[:3].upper()
        line = f' stream_data[{i}]: "{s.url}|{name}|{genre}|{lang}|{s.bitrate}|0"\n'
        lines.append(line)
    lines.append(FOOTER)
    with open(path, "w", encoding="utf-8") as f:
        f.writelines(lines)


def write_json(stations: list[Station], path: str) -> None:
    """Write the generated station list as JSON.

    The field names intentionally match the legacy ``siiTOjson.py`` output so
    existing consumers of ``live_streams.json`` do not need to change.
    """
    data = [
        {
            "index": i,
            "url": s.url,
            "name": s.name,
            "genre": s.genre,
            "country_code": s.language[:3].upper(),
            "bit_rate": int(s.bitrate),
            "playing": 0,
        }
        for i, s in enumerate(stations)
    ]
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")


def write_report(alive: list[Station], dead: list[Station], path: str) -> None:
    with open(path, "w", encoding="utf-8") as f:
        f.write("# Validation Report\n\n")
        f.write(f"**Live:** {len(alive)}  |  **Dead:** {len(dead)}\n\n")
        if dead:
            f.write("## Dead streams\n\n")
            f.write("| Station | URL | Country |\n|---|---|---|\n")
            f.writelines(f"| {s.name} | {s.url} | {s.country} |\n" for s in sorted(dead, key=lambda x: x.country))


def write_stations_md(alive: list[Station], dead: list[Station], path: str) -> None:
    alive_urls = {s.url for s in alive}
    all_stations = alive + dead

    by_country: dict[str, list[tuple[Station, bool]]] = defaultdict(list)
    for s in all_stations:
        by_country[s.country].append((s, s.url in alive_urls))

    today = datetime.now(UTC).date().strftime("%Y-%m-%d")
    total_live = len(alive)
    total_dead = len(dead)

    toc_entries = "\n".join(
        f"   - [{c}](#{c.lower().replace(' ', '-').replace('ü', 'u')})"
        for c in sorted(by_country)
    )

    with open(path, "w", encoding="utf-8") as f:
        f.write("# Status of radio stations\n\n")
        f.write(f"> Auto-generated by scraper on {today} — "
                f"{total_live} live, {total_dead} dead\n\n")
        f.write("## Table of Contents\n\n")
        f.write("1. Radio stations grouped by countries\n")
        f.write(toc_entries + "\n\n")
        f.write("---\n\n")
        f.write("| Legend | |\n|---|---:|\n")
        f.write("| Live / working | ✅ |\n")
        f.write("| Dead / not reachable | 🔴 |\n\n")
        f.write("---\n\n")

        for country in sorted(by_country):
            f.write(f"## {country}\n\n")
            for s, is_alive in sorted(by_country[country], key=lambda x: x[0].name):
                icon = "✅" if is_alive else "🔴"
                f.write(f"- {icon} {s.name}\n")
            f.write("\n")
